### ISSUE TITLE
Prefix support combined with equals-ignore-case

### ISSUE THREAD

**Issue by awsree** [aws/event-ruler#108]
## What is your idea?
Prefix works great on fields exact string match, but customer needs the ability to combine that with "equals-ignore-case" to be able to match complex custom event patterns where string values can come up with combined case combinations.

Example could be:
"query_text": [
     {
      "prefix": "ALTER DATABASE"
      }, 
     {
      "equals-ignore-case": "ALTER DATABASE"
    }
]

## Would you be willing to make the change? 
Yes

## Additional context
The above change will reduce lot of complex matching patterns, when there is a string that can come up in multiple case combinations from user/custom events - for instance a DB query text like above. The elaborate working way is to do this currently:
{
	"$or": [{
			"query_text": [{
				"prefix": "ALTER DATABASE"
			}]
		},
		{
			"query_text": [{
				"prefix": "ALTER database"
			}]
		},
		{
			"query_text": [{
				"prefix": "alter database"
			}]
		},
		{
			"query_text": [{
				"prefix": "alter DATABASE"
			}]
		}
	]
}

Add any other context (such as images, docs, posts) about the idea here.

**Comment by baldawar** [comment]
This is a neat way to add two matchers @awsree  but I'm worried that there will be ordering implications for anyone writing a rule. 
```
 {
     "query_text": [{
             "prefix": "ALTER DATABASE"
         },
         {
             "equals-ignore-case": "ALTER DATABASE"
         }
     ]
 }
``` 

Do you have any optinions on using nesting instead, like 
```
{
    "query_text": [{
        "prefix": {
            "equals-ignore-case": "ALTER DATABASE"
        }
    }]
}
```

this would be in-line with how anything-but & equals-ignore-case works as show in the last example within https://github.com/aws/event-ruler#anything-but-matching.

**Comment by awsree** [comment]
> This is a neat way to add two matchers @awsree but I'm worried that there will be ordering implications for anyone writing a rule.
> 
> ```
>  {
>      "query_text": [{
>              "prefix": "ALTER DATABASE"
>          },
>          {
>              "equals-ignore-case": "ALTER DATABASE"
>          }
>      ]
>  }
> ```
> 
> Do you have any optinions on using nesting instead, like
> 
> ```
> {
>     "query_text": [{
>         "prefix": {
>             "equals-ignore-case": "ALTER DATABASE"
>         }
>     }]
> }
> ```
> 
> this would be in-line with how anything-but & equals-ignore-case works as show in the last example within https://github.com/aws/event-ruler#anything-but-matching.

Yes ! I am good with the approach , that is in line with anything-but and equals-ignore-case
But currently that format, gives an error as prefix only support string at this point.

And as long as we can enhance and define a format for allowing equals-ignore-case to work with prefix, that would be great !

**Comment by baldawar** [comment]
You would need to implement a change similar to this commit to make it work : https://github.com/aws/event-ruler/commit/3b6202d5e39d55257235ef54de68ad20f1529de2 .

**Comment by baldawar** [comment]
btw, another option here would be to implement ignore case with wild-cards https://github.com/aws/event-ruler#wildcard-matching. This would allow for case insensitive matching for prefix, suffix, and any other sub-strings. Its more powerful.

**Comment by baldawar** [comment]
either, way if you plan to start on it, I'd like to first understand the use-case more and see if it makes sense to change the library to support it.

**Comment by rogeriosy** [comment]
Resolving this issue, since it has been implemented by the related PR.
