### ISSUE TITLE
give an JSON string, output a related string of event-ruler's rule

### ISSUE THREAD

**Issue by revolyw** [aws/event-ruler#150]
## What is your idea?
give an JSON string A, output a related string of event-ruler's rule. the related string should match A

## Would you be willing to make the change? 
No

## Additional context

Add any other context (such as images, docs, posts) about the idea here.

**Comment by baldawar** [comment]
hey @revolyw , could you give an example of what you're looking for. 

My first interpretation was that you want to pass a JSON string but not a JSON event like we support today ([link](https://github.com/aws/event-ruler/blob/364f2013bb1fd1b1a7a3b1090ab8d6eaa0c79873/src/main/software/amazon/event/ruler/GenericMachine.java#L84))
