### ISSUE TITLE
Cannot create GenericMachine using builder() for anything but Object without compiler warnings/errors

### ISSUE THREAD

**Issue by youngm** [aws/event-ruler#174]
I'd like to create a GenericMachine for Integer and I cannot do it without unsafe casts and compiler warnings.

## To Reproduce
Try these various ways to create a GenericMachine<Integer> without a warning or error. They all fail.
```
GenericMachine<Integer> try1Deprecated = new GenericMachine<Integer>();
GenericMachine<Integer> try1Raw = GenericMachine.builder().build();
GenericMachine<Integer> try2Raw =
    GenericMachine.builder().<GenericMachine<Integer>>build();
GenericMachine<Integer> try3NotVisible =
    new GenericMachine.Builder<GenericMachine<Integer>>().build();

```

## Expected behavior
Should be able to create a GenericMachine for a given type without a compiler warning.

Perhaps the build() method could accept a generic parameter?

## Environment:
Java 17

## Additional context
Sure, GenericMachine<Object> works but why make it generic if there isn't a clean way to make an instance of any other type?

**Comment by baldawar** [comment]
Merged https://github.com/aws/event-ruler/pull/175. thanks @youngm
