### ISSUE TITLE
Request for Go SDK for event-ruler

### ISSUE THREAD

**Issue by sathishdv** [aws/event-ruler#206]
## What is your idea?
Idea is to have a Go version of this library. Is there something in-progress / in roadmap?

## Additional context

Add any other context (such as images, docs, posts) about the idea here.

**Comment by embano1** [comment]
@sathishdv you might want to take a look at @timbray's Quamina project

**Comment by sathishdv** [comment]
@embano1 Thank you, the Quamina project looks what I wanted. Will play around with it to see if that's a compatible solutions for my use case. 🙇
