### ISSUE TITLE
Make library available in maven 

### ISSUE THREAD

**Issue by baldawar** [aws/event-ruler#27]
## What is your idea?

Make the library available in maven so that we can then consume is again internally. This was the code from the internal version can be replaced with library calls. We haven't done it yet because this pkg isn;t public/

## Would you be willing to make the change? 

Yes

## Additional context

This may be slightly big change if we need to change the folder structure.  When I created the pkg, I followed a non-standard format (rookie mistake, I swear).

**Comment by baldawar** [comment]
https://issues.sonatype.org/browse/OSSRH-84436

**Comment by baldawar** [comment]
🤯

**Comment by baldawar** [comment]
https://issues.sonatype.org/browse/OSSRH-84940

**Comment by baldawar** [comment]
https://central.sonatype.dev/artifact/software.amazon.event.ruler/event-ruler/1.0.1/overview

**Comment by TrumanDu** [comment]
Wait to finish!

**Comment by baldawar** [comment]
this is done https://mvnrepository.com/artifact/software.amazon.event.ruler/event-ruler.
