### ISSUE TITLE
NULL returns in RuleCompiler#check

### ISSUE THREAD

**Issue by h1alexbel** [aws/event-ruler#59]
So, in this code, you returning null after processing the JSON, but initially, the method was designed that way, to return String.
Usually NULL means higher complexity and problems.

```
public static String check(final Reader source) {
    try {
      doCompile(JSON_FACTORY.createParser(source));
      return null;
    } catch (Exception e) {
      return e.getLocalizedMessage();
    }
  }
  ```

**Comment by timbray** [comment]
The intent is that if there is no problem you get NULL, if the return value is non-null that means there's a problem and also you got a helpful error message.  This is a reasonably common pattern?

**Comment by baldawar** [comment]
The pattern isn't common anymore as folks don't expect null unless documented. In this case, we do document. also, checks are commonly expected to not return values, to null here won't hurt. At most we can deprecate this method and instead change signature to `public static void check(....)` . 

Given the low activity on this issue, I'm going to close this. Folks can reopen if they think we need to drive this to a different conclusion.
