### ISSUE TITLE
Support for suffix with anything-but filtering.

### ISSUE THREAD

**Issue by ryan-neff** [aws/event-ruler#66]
## What is your idea?
the `prefix` comparison key can currently be used in conjunction with `anything-but` like so:
```
"state": [ { "anything-but": { "prefix": "init" } } ]
```

**This feature request is simply to have this same support, but for the recently released `suffix` key.** 

Example:
```
"arn": [ { "anything-but": { "suffix": "ServiceRole" } } ]
```

## Would you be willing to make the change? 
Yes, but this would be my first contribution to the project.

**Comment by baldawar** [comment]
This makes sense. If suffix isn't supported today, its likely due to an error (probably a missed entry within an configuration). Along with the change, I would recommend to also add a unit test.

**Comment by baldawar** [comment]
Here's an example of how prefix is configured in today 

https://github.com/aws/event-ruler/blob/1b4281e3366534adb9b8dd1544548c14e1817d64/src/main/software/amazon/event/ruler/RuleCompiler.java#L302

**Comment by schenksj** [comment]
I need this too!  I'll go ahead and submit the PR.

**Comment by ryan-neff** [comment]
Yes. #76 handled this issue request
