### ISSUE TITLE
Support for anything-but/ignore-case

### ISSUE THREAD

**Issue by schenksj** [aws/event-ruler#70]
## What is your idea?
Add a permutation of anything-but that is case insensitive, gaining parity with `equals-ignore-case`.

We have a need to exclude without case sensitivity for use cases such as windows file path processing.

```
{
  "detail": {
    "command_path": [ { "anything-but": {"ignore-case": [ "c:\windows", "c:\Program Files" ] } } ]
  }
}
```
'
## Would you be willing to make the change? 
Yes

## Additional context

Add any other context (such as images, docs, posts) about the idea here.

**Comment by baldawar** [comment]
If we implement `ignore-case` as a matcher of its own. It'll paves the way to work with  Anything-But and other matchers like Prefix, Suffix, and more in future.

```
{
	"detail": {
		"command_path": [{
			"anything-but": {
				"ignore-case":  [ "c:\windows", "c:\Program Files"]
			}
		}]
	}
}
```

**Comment by schenksj** [comment]
@baldawar - I like it. Will update my draft PR accordingly and open it for review.

**Comment by schenksj** [comment]
(Note updated the original issue to avoid confusion)

**Comment by schenksj** [comment]
deployed to prod on 2/16/2023 in release 1.2.0
